import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import './model/air-result.dart';
import './api-key.dart';

class FineDust extends StatefulWidget {
  static const routeName = '/fine-dust';

  @override
  _FineDustState createState() => _FineDustState();
}

class _FineDustState extends State<FineDust> {
  Autogenerated _result;
  DateTime dateTime = DateTime.now();

  Future<Autogenerated> getDataFromAPI() async {
    var response = await http
        .get('https://api.airvisual.com/v2/nearest_city?key=$api_key');

    return Autogenerated.fromJson(json.decode(response.body));
  }

  Color getColor(Autogenerated result) {
    if (result.data.current.pollution.aqius <= 50) {
      return Colors.greenAccent;
    } else if (result.data.current.pollution.aqius <= 100) {
      return Colors.yellow;
    } else if (result.data.current.pollution.aqius <= 150) {
      return Colors.orange;
    } else {
      return Colors.red;
    }
  }

  String getString(Autogenerated result) {
    if (result.data.current.pollution.aqius <= 50) {
      return 'Good';
    } else if (result.data.current.pollution.aqius <= 100) {
      return 'Normal';
    } else if (result.data.current.pollution.aqius <= 150) {
      return 'Not Good';
    } else {
      return 'Bad';
    }
  }

  @override
  void didChangeDependencies() async {
    super.didChangeDependencies();

    Autogenerated result = await getDataFromAPI();

    setState(() {
      _result = result;
      dateTime = DateTime.now();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: _result == null
            ? CircularProgressIndicator()
            : Padding(
                padding: const EdgeInsets.all(8.0),
                child: Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      Text(
                        'Fine Dust Measuer API',
                        style: TextStyle(
                          fontSize: 25.0,
                        ),
                      ),
                      const SizedBox(height: 16.0),
                      Card(
                        elevation: 4.0,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(10),
                        ),
                        child: Column(
                          children: <Widget>[
                            Container(
                              padding: const EdgeInsets.all(8.0),
                              color: getColor(_result),
                              child: Row(
                                mainAxisAlignment:
                                    MainAxisAlignment.spaceAround,
                                children: <Widget>[
                                  Text(
                                    'Aqius: ${_result.data.current.pollution.aqius}',
                                    style: TextStyle(fontSize: 40.0),
                                  ),
                                  Text(getString(_result),
                                      style: TextStyle(fontSize: 20.0)),
                                ],
                              ),
                            ),
                            Padding(
                              padding: const EdgeInsets.all(8.0),
                              child: Row(
                                mainAxisAlignment:
                                    MainAxisAlignment.spaceAround,
                                children: <Widget>[
                                  Row(
                                    children: <Widget>[
                                      Image.network(
                                        'https://airvisual.com/images/${_result.data.current.weather.ic}.png',
                                        width: 25.0,
                                        height: 25.0,
                                      ),
                                      const SizedBox(width: 16.0),
                                      Text(
                                        'Tp: ${_result.data.current.weather.tp}℃',
                                        style: TextStyle(fontSize: 16.0),
                                      ),
                                    ],
                                  ),
                                  Text(
                                    'Hu: ${_result.data.current.weather.hu}',
                                  ),
                                  Text(
                                    'WS: ${_result.data.current.weather.ws}',
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 16.0),
                      Text('${dateTime.toString()}'),
                      const SizedBox(height: 16.0),
                      RaisedButton(
                        onPressed: () async {
                          Autogenerated result = await getDataFromAPI();

                          setState(() {
                            _result = result;
                            dateTime = DateTime.now();
                          });
                        },
                        color: Colors.orange,
                        child: Icon(
                          Icons.refresh,
                          color: Colors.white,
                        ),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(25),
                        ),
                      ),
                      const SizedBox(height: 16.0),
                    ],
                  ),
                ),
              ),
      ),
    );
  }
}
