import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import '../lib/fine-dust.dart';
import '../lib/api-key.dart';
import '../lib/model/air-result.dart';

void main() {
  test('http Communication Test', () async {
    var response = await http
        .get('https://api.airvisual.com/v2/nearest_city?key=$api_key');

    expect(response.statusCode, 200);

    Autogenerated result = Autogenerated.fromJson(json.decode(response.body));

    expect(result.status, 'success');
  });
}
