import 'dart:convert';
import 'package:rxdart/rxdart.dart';
import 'package:http/http.dart' as http;
import '../model/air-result.dart';
import '../api-key.dart';

class AirBloc {
  AirBloc() {
    streamToSubject();
  }

  final _airBlocSubject = BehaviorSubject<Autogenerated>();

  Future<Autogenerated> getDataFromAPI() async {
    var response = await http
        .get('https://api.airvisual.com/v2/nearest_city?key=$api_key');

    return Autogenerated.fromJson(json.decode(response.body));
  }

  void streamToSubject() async {
    print(DateTime.now());
    var airResult = await getDataFromAPI();
    _airBlocSubject.add(airResult);
  }

  Stream<Autogenerated> get airBlocStream => _airBlocSubject.stream;
}
